apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vpro-ingress
  labels:
    app.kubernetes.io/name: myingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: vproapp.rockyrohith.work.gd  # Replace with your domain or IP (e.g., vpro.example.com)
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: vproapp-service
            port:
              number: 8080
